// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXFTzDOyFmkJmeIr_PHs_Us9C1KrR0ikQ',
    appId: '1:759788532035:web:528b380bff35fe42977ff6',
    messagingSenderId: '759788532035',
    projectId: 'tokan-57582',
    authDomain: 'tokan-57582.firebaseapp.com',
    storageBucket: 'tokan-57582.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYTDmerhK_sPVc99B5ac9M5TRzQ_2EuHA',
    appId: '1:759788532035:android:32190107d1f95e08977ff6',
    messagingSenderId: '759788532035',
    projectId: 'tokan-57582',
    storageBucket: 'tokan-57582.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAufPs9FNUGyn834QyD3ZzabgqJX8c4Sgc',
    appId: '1:759788532035:ios:b17907cfc6397d54977ff6',
    messagingSenderId: '759788532035',
    projectId: 'tokan-57582',
    storageBucket: 'tokan-57582.firebasestorage.app',
    androidClientId: '759788532035-fp5t4jnc9s15jescgondctb10o6cv2u3.apps.googleusercontent.com',
    iosClientId: '759788532035-3ii4765n4vfvrlep29707hdj2rtigsuc.apps.googleusercontent.com',
    iosBundleId: 'com.tokan.tokan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAufPs9FNUGyn834QyD3ZzabgqJX8c4Sgc',
    appId: '1:759788532035:ios:b17907cfc6397d54977ff6',
    messagingSenderId: '759788532035',
    projectId: 'tokan-57582',
    storageBucket: 'tokan-57582.firebasestorage.app',
    androidClientId: '759788532035-4no5e9r2ga6ku43vrr1okjmrlhvbkhl7.apps.googleusercontent.com',
    iosClientId: '759788532035-3ii4765n4vfvrlep29707hdj2rtigsuc.apps.googleusercontent.com',
    iosBundleId: 'com.tokan.tokan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXFTzDOyFmkJmeIr_PHs_Us9C1KrR0ikQ',
    appId: '1:759788532035:web:0ac2b954f17685d7977ff6',
    messagingSenderId: '759788532035',
    projectId: 'tokan-57582',
    authDomain: 'tokan-57582.firebaseapp.com',
    storageBucket: 'tokan-57582.firebasestorage.app',
  );

}